import {
  Hotel,
  IndividualRoom,
  Reservation,
  GuestProfile,
  StaffMember,
  HousekeepingTask,
  Review,
  TenantApplication,
  PayoutRequest,
  Destination,
  MobilityVehicle,
  DMCExperience,
  FlightRoute,
  NotificationItem,
  PublicPlace,
  ListingCategory,
} from './types';

// ==========================================
// 1. FIRST-CLASS DESTINATIONS DATABASE
// ==========================================
export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'dest-lagos',
    slug: 'lagos',
    city: 'Lagos',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Coastal Energy, Modern Architecture & Vibrant Terroir',
    description: 'A dynamic metropolis where Atlantic coastal breezes meet contemporary luxury retreats in Victoria Island, Ikoyi, and Eko Atlantic.',
    heroImage: 'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Lekki Conservation Sanctuary', 'Nike Art Gallery', 'Tarkwa Bay Private Yacht Haven', 'Victoria Island Culinary Quarter'],
    travelTips: ['Best visited November through March', 'Chauffeur airport transfer recommended from Murtala Muhammed International'],
    featured: true,
    climate: 'Tropical Savanna (28°C avg)',
    bestTimeToVisit: 'Nov – March',
  },
  {
    id: 'dest-abuja',
    slug: 'abuja',
    city: 'Abuja',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Monumental Granite Vistas & Diplomatic Serenity',
    description: 'Nigeria’s purpose-built capital framed by the iconic Aso Rock monolith, lush botanical gardens, and refined palatial residences.',
    heroImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Aso Rock Monolith', 'Millennium Park Botanical Arboretum', 'Maitama Diplomatic District', 'Usuma Dam Vista'],
    featured: true,
    climate: 'Tropical Continental (26°C avg)',
    bestTimeToVisit: 'Oct – April',
  },
  {
    id: 'dest-ibadan',
    slug: 'ibadan',
    city: 'Ibadan',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Historic Hills & Rich Yoruba Heritage',
    description: 'An ancient city of brown roofs and rolling green ridges, blossoming with bespoke eco-sanctuaries and cultural heritage sites.',
    heroImage: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Bower’s Tower Panoramas', 'Agodi Botanical Gardens', 'IITA Forest Reserve'],
    featured: false,
    climate: 'Warm Tropical (27°C avg)',
    bestTimeToVisit: 'Nov – Feb',
  },
  {
    id: 'dest-dubai',
    slug: 'dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
    headline: 'Futuristic Skyline, Arabian Dunes & Ultra-Luxury Living',
    description: 'The global benchmark for architectural daring, Michelin-starred culinary artistry, and private Arabian Gulf beach sanctuaries.',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Palm Jumeirah Archipelago', 'Dubai Opera & Downtown Fountains', 'Al Marmoom Desert Conservation Reserve'],
    featured: true,
    climate: 'Desert Subtropical (24°C winter / 38°C summer)',
    bestTimeToVisit: 'Nov – April',
  },
  {
    id: 'dest-abu-dhabi',
    slug: 'abu-dhabi',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    region: 'Middle East',
    headline: 'Island Sanctuaries & Cultural Masterpieces',
    description: 'From the Louvre Abu Dhabi dome to pristine Saadiyat Island beaches where hawksbill turtles nest in turquoise waters.',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [],
    attractions: ['Louvre Abu Dhabi', 'Sheikh Zayed Grand Mosque', 'Saadiyat Beach Sanctuary'],
    featured: false,
    climate: 'Arid Maritime',
    bestTimeToVisit: 'Oct – April',
  },
  {
    id: 'dest-paris',
    slug: 'paris',
    city: 'Paris',
    country: 'France',
    region: 'Western Europe',
    headline: 'Timeless Haussmannian Elegance & Haute Cuisine',
    description: 'Grand boulevards, private palace suites overlooking the Seine, and secluded courtyard boutique hotels.',
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Musée d’Orsay & Louvre', 'Jardin des Tuileries', 'Place Vendôme Jewelers', 'Le Marais Mansions'],
    featured: true,
    climate: 'Oceanic Mild',
    bestTimeToVisit: 'April – Oct',
  },
  {
    id: 'dest-santorini',
    slug: 'santorini',
    city: 'Santorini',
    country: 'Greece',
    region: 'Southern Europe',
    headline: 'Volcanic Calderas, Whitewashed Caves & Twilight Sunsets',
    description: 'Iconic clifftop cave sanctuaries carved into volcanic rock, offering heated infinity pools suspended over the sapphire Aegean Sea.',
    heroImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Oia Caldera Sunset Rim', 'Akrotiri Prehistoric Ruins', 'Red Sand Beach & Ammoudi Bay'],
    featured: true,
    climate: 'Mediterranean Sun (27°C avg summer)',
    bestTimeToVisit: 'May – Oct',
  },
  {
    id: 'dest-cape-town',
    slug: 'cape-town',
    city: 'Cape Town',
    country: 'South Africa',
    region: 'Southern Africa',
    headline: 'Granite Peaks, Atlantic Breakers & Wineland Estates',
    description: 'Where dramatic Table Mountain plunges into two oceans, bordered by historic Constantia vineyards and Camps Bay modern villas.',
    heroImage: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Table Mountain Aerial Cableway', 'Camps Bay Sunset Strip', 'Cape Point Nature Reserve', 'Franschhoek Wine Tram'],
    featured: true,
    climate: 'Mediterranean Coastal',
    bestTimeToVisit: 'Dec – March',
  },
  {
    id: 'dest-maldives',
    slug: 'maldives',
    city: 'North Malé Atoll',
    country: 'Maldives',
    region: 'Indian Ocean',
    headline: 'Overwater Villas & Luminous Coral Lagoons',
    description: 'Ultra-private stilt villas suspended over crystalline turquoise waters with private house reef diving.',
    heroImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [],
    attractions: ['Baa Atoll Biosphere Reserve', 'Undersea Dining Cellars', 'Bioluminescent Plankton Beaches'],
    featured: true,
    climate: 'Tropical Monsoonal',
    bestTimeToVisit: 'Nov – April',
  },
  {
    id: 'dest-inverness',
    slug: 'inverness',
    city: 'Inverness',
    country: 'United Kingdom',
    region: 'Northern Europe',
    headline: 'Highland Lochs, Ancient Pines & Heritage Castles',
    description: 'Secluded baronial stone estates surrounded by heather-clad glens, peat-smoked single malt distilleries, and deep freshwater lochs.',
    heroImage: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Loch Ness Panoramic Glens', 'Urquhart Castle Ruins', 'Cairngorms National Forest', 'Speyside Whisky Route'],
    featured: true,
    climate: 'Temperate Maritime',
    bestTimeToVisit: 'May – Sept',
  },
];

// ==========================================
// 2. REAL ONBOARDED HOTELS (Empty until onboarded via OPERATE)
// ==========================================
// 2. REAL ONBOARDED HOTELS (Empty until onboarded via OPERATE)
// ==========================================
export const INITIAL_HOTELS: Hotel[] = [];

// ==========================================
// 3. MOBILITY / CARS / CHAUFFEUR SERVICES
// ==========================================
export const INITIAL_VEHICLES: MobilityVehicle[] = [
  {
    id: 'veh-range-rover',
    name: 'Range Rover Autobiography SV LWB',
    category: 'SUV',
    passengers: 4,
    luggage: 4,
    transmission: 'Automatic',
    pricePerDay: 450,
    priceWithDriverPerHour: 85,
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1000&q=80',
    features: ['Executive Rear Seating', 'Panoramic Glass Sunroof', 'Chilled Console Fridge', 'Active Noise Cancellation', 'Armored Protection Available'],
    availableCities: ['Lagos', 'Abuja', 'Dubai', 'Paris', 'Nice'],
  },
  {
    id: 'veh-mercedes-s-class',
    name: 'Mercedes-Maybach S 680 4MATIC',
    category: 'Luxury Sedan',
    passengers: 3,
    luggage: 3,
    transmission: 'Automatic',
    pricePerDay: 580,
    priceWithDriverPerHour: 95,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1000&q=80',
    features: ['First-Class Rear Reclining Lounge', 'Silver Champagne Flutes', 'Burmester 4D High-End Sound', 'Rear Entertainment Screens'],
    availableCities: ['Lagos', 'Dubai', 'Paris', 'Nice', 'Santorini'],
  },
  {
    id: 'veh-mercedes-v-class',
    name: 'Mercedes-Benz V-Class VIP Executive Lounge',
    category: 'Executive Van',
    passengers: 6,
    luggage: 7,
    transmission: 'Automatic',
    pricePerDay: 390,
    priceWithDriverPerHour: 75,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80',
    features: ['Face-to-Face Conference Seating', 'Foldaway Mahogany Tables', 'Wi-Fi Hotspot 5G', 'Dual Privacy Scrim Glass'],
    availableCities: ['Lagos', 'Abuja', 'Dubai', 'Paris', 'Inverness'],
  },
  {
    id: 'veh-porsche-targa',
    name: 'Porsche 911 Targa 4 GTS Heritage',
    category: 'Convertible',
    passengers: 2,
    luggage: 2,
    transmission: 'Automatic',
    pricePerDay: 620,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80',
    features: ['Aero Targa Open Roof', 'Sport Chrono Package', 'Bespoke Houndstooth Leather', 'All-Wheel Drive Coastal Grip'],
    availableCities: ['Nice', 'Dubai', 'Santorini', 'Cape Town'],
  },
];

// ==========================================
// 4. DMC / EXPERIENCES & TOURS
// ==========================================
export const INITIAL_EXPERIENCES: DMCExperience[] = [
  {
    id: 'dmc-lagos-art-culinary',
    title: 'Lagos Modern Masterpieces & Atlantic Yacht Safari',
    slug: 'lagos-modern-art-yacht-safari',
    category: 'Tours',
    destinationCity: 'Lagos',
    destinationCountry: 'Nigeria',
    durationDays: 3,
    pricePerPerson: 1250,
    heroImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Private private curator tour of Nike Art Gallery with founder Madam Nike Okundaye',
      'Sunset champagne cruise along Tarkwa Bay & Eko Atlantic coastline on private 55ft yacht',
      'Exclusive 7-course tasting menu with leading contemporary Nigerian culinary pioneers',
    ],
    includedServices: ['Private Chauffeur', 'Yacht Charter', 'All Tastings & Admissions', 'Dedicated Concierge Escort'],
    description: 'An immersive 3-day deep dive into the creative explosion and coastal opulence of modern Lagos, curated for discerning collectors and cultural connoisseurs.',
  },
  {
    id: 'dmc-santorini-catamaran',
    title: 'Santorini Caldera Sunset Catamaran & Volcanic Terroir',
    slug: 'santorini-caldera-catamaran-terroir',
    category: 'Tours',
    destinationCity: 'Santorini',
    destinationCountry: 'Greece',
    durationDays: 1,
    pricePerPerson: 420,
    heroImage: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Private Lagoon 450 catamaran charter navigating the volcanic caldera and hot springs',
      'Gourmet barbecue prepared onboard with fresh Aegean seafood and indigenous herbs',
      'Exclusive private cellar tasting of rare vintage Assyrtiko wines in Pyrgos',
    ],
    includedServices: ['Catamaran Charter', 'Sommelier Guided Tasting', 'Gourmet Lunch & Drinks', 'Hotel Transfers'],
    description: 'Sail the sapphire waters of the volcanic caldera, swim in secluded mineral coves, and savor rare volcanic wines as the sun sets over Oia.',
  },
  {
    id: 'dmc-honeymoon-retreat',
    title: 'The Sovereign Aegean & Maldivian Honeymoon Odyssey',
    slug: 'sovereign-aegean-honeymoon-odyssey',
    category: 'Honeymoon Packages',
    destinationCity: 'Santorini',
    destinationCountry: 'Greece',
    durationDays: 7,
    pricePerPerson: 3800,
    heroImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Cliffside private plunge pool cave villa with daily in-suite vintage champagne breakfast',
      'Couples twilight herbal thermal spa ritual under the Mediterranean stars',
      'Helicopter aerial tour over Mykonos, Delos, and the Cycladic archipelago',
    ],
    includedServices: ['7 Nights Luxury Stay', 'Helicopter Transfers', 'All Spa Rituals', 'Private Concierge Manager'],
    description: 'Designed for couples embarking on a lifetime together, combining absolute privacy, restorative romance, and world-class hospitality.',
  },
  {
    id: 'dmc-events-gala',
    title: 'Bespoke Destination Weddings & Executive Summits',
    slug: 'destination-weddings-executive-summits',
    category: 'Events',
    destinationCity: 'Dubai',
    destinationCountry: 'United Arab Emirates',
    durationDays: 4,
    pricePerPerson: 2500,
    heroImage: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Exclusive buyout coordination of private beachfront island estates',
      'World-class acoustic staging, floral master installations, and Michelin culinary brigades',
      'Full VIP protocol security and discrete diplomatic delegation handling',
    ],
    includedServices: ['Event Production Director', 'Full Venue Buyout Management', 'VIP Transport Fleet', 'Catering Architecture'],
    description: 'Turnkey event planning and executive destination management for milestones, international summits, and royal ceremonies.',
  },
];

// ==========================================
// 5. FLIGHT DISCOVERY ROUTES
// ==========================================
export const INITIAL_FLIGHTS: FlightRoute[] = [
  {
    id: 'fl-lon-los',
    fromCity: 'London',
    fromCode: 'LHR',
    toCity: 'Lagos',
    toCode: 'LOS',
    airline: 'Virgin Atlantic / British Airways',
    duration: '6h 35m',
    indicativePrice: 780,
    cabinClasses: ['Economy', 'Premium Economy', 'Upper Class / Club World'],
    direct: true,
  },
  {
    id: 'fl-cdg-dxb',
    fromCity: 'Paris',
    fromCode: 'CDG',
    toCity: 'Dubai',
    toCode: 'DXB',
    airline: 'Emirates / Air France',
    duration: '6h 45m',
    indicativePrice: 650,
    cabinClasses: ['Economy', 'Business', 'First Class Suite'],
    direct: true,
  },
  {
    id: 'fl-jfk-nce',
    fromCity: 'New York',
    fromCode: 'JFK',
    toCity: 'Nice',
    toCode: 'NCE',
    airline: 'La Compagnie / Delta',
    duration: '7h 50m',
    indicativePrice: 940,
    cabinClasses: ['All-Business Class', 'Delta One'],
    direct: true,
  },
  {
    id: 'fl-fra-jtr',
    fromCity: 'Frankfurt',
    fromCode: 'FRA',
    toCity: 'Santorini',
    toCode: 'JTR',
    airline: 'Lufthansa',
    duration: '3h 10m',
    indicativePrice: 320,
    cabinClasses: ['Economy', 'Business'],
    direct: true,
  },
];

// ==========================================
// 6. PUBLIC ATTRACTIONS & PLACES (NO PROVIDER ONBOARDING REQUIRED)
// ==========================================
export const INITIAL_PUBLIC_PLACES: PublicPlace[] = [
  {
    id: 'pub-lekki-conservation',
    slug: 'lekki-conservation-sanctuary',
    name: 'Lekki Conservation Sanctuary & Canopy Walk',
    category: 'nature',
    description: 'A 78-hectare natural rainforest and coastal mangrove swamp reserve featuring Africa’s longest elevated canopy walkway, native flora, and free-roaming wildlife.',
    location: {
      city: 'Lagos',
      country: 'Nigeria',
      address: 'KM 19 Lekki-Epe Expressway, Lekki Peninsula',
    },
    heroImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80'],
    facilities: ['Elevated Canopy Walkway', 'Picnic Arboretums', 'Nature Trails', 'Bird Watching Towers'],
    visitorInfo: {
      openingHours: '08:30 – 17:00 Daily',
      entryFee: '₦2,500 per adult',
      bestTimeToVisit: 'Morning hours (09:00 - 11:30)',
      contactPhone: '+234 802 345 6789',
      website: 'https://ncfnigeria.org',
    },
    verificationStatus: 'verified',
    verificationSource: 'Nigerian Conservation Foundation & HotelStay Editorial Team',
    isBookable: true,
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'pub-nike-art-gallery',
    slug: 'nike-art-gallery-culture',
    name: 'Nike Art Gallery & Cultural Centre',
    category: 'cultural',
    description: 'A four-story architectural haven housing over 25,000 African contemporary artworks, batik textile installations, and traditional bronze sculptures.',
    location: {
      city: 'Lagos',
      country: 'Nigeria',
      address: '2 Oba Yekini Street, Elegushi Royal Beach Road, Ikate',
    },
    heroImage: 'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=800&q=80'],
    facilities: ['Guided Art Tours', 'Batik Craft Workshops', 'Gift Shop & Collectibles', 'Courtyard Lounge'],
    visitorInfo: {
      openingHours: '10:00 – 18:00 (Mon-Sat), 13:00 - 18:00 (Sun)',
      entryFee: 'Free Admission',
      bestTimeToVisit: 'Afternoon',
      website: 'https://nikeart.com',
    },
    verificationStatus: 'verified',
    verificationSource: 'Lagos State Ministry of Tourism',
    isBookable: false,
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'pub-aso-rock-view',
    slug: 'aso-rock-monolith-viewpoint',
    name: 'Aso Rock Monolith & Botanical Gardens',
    category: 'landmark',
    description: 'The iconic 400-metre granite monolith dominating the skyline of Abuja, surrounded by manicured government parks and natural springs.',
    location: {
      city: 'Abuja',
      country: 'Nigeria',
      address: 'Asokoro District Outlook, Three Arms Zone',
    },
    heroImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80'],
    facilities: ['Panoramic Observation Terrace', 'Public Gardens', 'Security Guarded Access'],
    visitorInfo: {
      openingHours: 'Daylight hours',
      entryFee: 'Public Space',
      bestTimeToVisit: 'Golden Hour Sunset',
    },
    verificationStatus: 'unverified',
    verificationSource: 'Community Sourced Information',
    isBookable: false,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'pub-louvre-abu-dhabi',
    slug: 'louvre-abu-dhabi-museum',
    name: 'Louvre Abu Dhabi Museum & Floating Dome',
    category: 'museum',
    description: 'Jean Nouvel’s architectural masterpiece featuring a rain-of-light dome floating over the Arabian Gulf with global art masterworks.',
    location: {
      city: 'Abu Dhabi',
      country: 'United Arab Emirates',
      address: 'Saadiyat Cultural District',
    },
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80'],
    facilities: ['Kayaking under Dome', 'Museum Cafe', 'Children’s Museum', 'Audioguide Services'],
    visitorInfo: {
      openingHours: '10:00 – 18:30 (Tues-Sun)',
      entryFee: 'AED 63 per ticket',
      website: 'https://louvreabudhabi.ae',
    },
    verificationStatus: 'verified',
    verificationSource: 'Department of Culture and Tourism Abu Dhabi',
    isBookable: true,
    createdAt: '2026-02-15T10:00:00Z',
  },
];

// ==========================================
// 7. OPERATIONAL COLLECTIONS & PRE-APPROVED LISTINGS
// ==========================================
export const INITIAL_APPROVED_LISTINGS: Hotel[] = [
  {
    id: 'hotel-eko-royal',
    slug: 'eko-royal-palace-suite',
    name: 'The Eko Royal Palace & Oceanside Suites',
    tagline: 'Private Atlantic oceanfront sanctuary with personal butler service',
    description: 'Surrounded by lush private palms in Victoria Island, featuring private infinity pools, Michelin-starred coastal dining, and direct yacht berth access.',
    category: 'hotels',
    location: {
      city: 'Lagos',
      country: 'Nigeria',
      address: 'Plot 1415 Victoria Island Coastal Boulevard',
      latitude: 6.4281,
      longitude: 3.4219,
      neighborhoodDescription: 'Victoria Island Executive Oceanfront',
    },
    starRating: 5,
    guestRating: 4.9,
    reviewCount: 128,
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    ],
    startingPrice: 650,
    currency: 'USD',
    currencySymbol: '$',
    featured: true,
    luxuryTier: '5-Star Luxury',
    amenities: ['Private Beach', '24/7 Butler Service', 'Infinity Pool', 'Helipad', 'Spa & Wellness'],
    roomTypes: [
      {
        id: 'rt-eko-presidential',
        hotelId: 'hotel-eko-royal',
        name: 'Presidential Ocean Suite',
        slug: 'presidential-ocean-suite',
        description: '220 sqm suite with private plunge pool and panoramic Atlantic ocean vistas.',
        sizeSqFt: 2368,
        bedType: 'Emperor King',
        maxGuests: 4,
        basePricePerNight: 1200,
        images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80'],
        amenities: ['Private Pool', 'Jacuzzi', 'Marble Bath', 'Personal Butler'],
        availableCount: 3,
      },
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellationDeadlineHours: 24,
      cancellationFeePercent: 0,
      petPolicy: 'Pets permitted upon request',
      smokingPolicy: 'Non-smoking suites',
      childPolicy: 'Children welcome',
    },
    contactEmail: 'concierge@ekoroyal.com',
    contactPhone: '+234 1 270 0000',
    status: 'live',
    commissionRatePercent: 12.5,
    subscriptionPlan: 'enterprise',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rental-ikoyi-villa',
    slug: 'ikoyi-waterfront-architectural-villa',
    name: 'Ikoyi Waterfront Architectural Penthouse Villa',
    tagline: 'Ultra-modern 4-bedroom estate with private boat dock',
    description: 'Secluded waterfront sanctuary in Ikoyi featuring floor-to-ceiling glass, automated smart home systems, infinity pool, and private jetty.',
    category: 'holiday_rentals',
    categoryDetails: {
      propertyType: 'Waterfront Villa',
      bedroomsCount: 4,
      bathroomsCount: 5,
      maxCapacity: 8,
      minimumStayNights: 2,
      nightlyRate: 950,
    },
    location: {
      city: 'Lagos',
      country: 'Nigeria',
      address: 'Glover Road Waterfront Estate, Ikoyi',
      latitude: 6.452,
      longitude: 3.435,
      neighborhoodDescription: 'Ikoyi Private Diplomatic Enclave',
    },
    starRating: 5,
    guestRating: 4.95,
    reviewCount: 42,
    heroImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1600&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80'],
    startingPrice: 950,
    currency: 'USD',
    currencySymbol: '$',
    featured: true,
    luxuryTier: 'Beachfront Villa',
    amenities: ['Private Jetty', 'Smart Automation', 'Infinite Pool', 'Private Chef Kitchen', '24/7 Armed Security'],
    roomTypes: [],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '11:00',
      cancellationDeadlineHours: 48,
      cancellationFeePercent: 10,
      petPolicy: 'No pets',
      smokingPolicy: 'Outdoor terraces only',
      childPolicy: 'Family friendly',
    },
    contactEmail: 'villas@hotelstay.com',
    contactPhone: '+234 809 111 2222',
    status: 'approved',
    commissionRatePercent: 12.5,
    subscriptionPlan: 'pro',
    createdAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'trans-armored-fleet',
    slug: 'executive-chauffeur-armored-fleet',
    name: 'HotelStay Diplomatic Chauffeur & Armored Mobility',
    tagline: 'VIP airport escort, Maybach S-Class & Range Rover fleet',
    description: 'Bespoke chauffeur services across West Africa and Gulf cities with certified close-protection drivers, real-time GPS tracking, and luxury refreshment amenities.',
    category: 'transport',
    categoryDetails: {
      vehicleType: 'Executive SUV & Luxury Sedan',
      passengerCapacity: 4,
      luggageCapacity: 4,
      driverOption: 'with_driver',
      dailyRate: 480,
      hourlyRate: 75,
      serviceAreas: ['Lagos', 'Abuja', 'Port Harcourt', 'Dubai'],
    },
    location: {
      city: 'Lagos',
      country: 'Nigeria',
      address: 'Murtala Muhammed International Airport VIP Terminal',
      latitude: 6.5774,
      longitude: 3.321,
      neighborhoodDescription: 'Airport Aviation Enclave',
    },
    starRating: 5,
    guestRating: 5.0,
    reviewCount: 89,
    heroImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1600&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80'],
    startingPrice: 480,
    currency: 'USD',
    currencySymbol: '$',
    featured: true,
    luxuryTier: '5-Star Luxury',
    amenities: ['Close Protection Driver', 'Wi-Fi Onboard', 'Chilled Mineral Water', 'Airport Fast-Track'],
    roomTypes: [],
    policies: {
      checkInTime: '00:00',
      checkOutTime: '23:59',
      cancellationDeadlineHours: 12,
      cancellationFeePercent: 0,
      petPolicy: 'Service animals accepted',
      smokingPolicy: 'Strictly non-smoking',
      childPolicy: 'Child seats provided upon request',
    },
    contactEmail: 'mobility@hotelstay.com',
    contactPhone: '+234 700 468 3578',
    status: 'approved',
    commissionRatePercent: 12.5,
    subscriptionPlan: 'pro',
    createdAt: '2026-02-15T00:00:00Z',
  },
  {
    id: 'tour-[#001]',
    slug: 'private-yacht-charter-tarkwa-bay',
    name: 'Private Yacht Cruise & Tarkwa Bay Private Beach Club',
    tagline: 'Full-day catamaran charter with private chef & jet ski sports',
    description: 'Cruise past the Lagos skyline aboard a 65ft luxury catamaran to a private beach lounge with seafood barbecue, champagne tasting, and watersports.',
    category: 'tours_experiences',
    categoryDetails: {
      durationHours: 8,
      groupSizeLimit: 12,
      includedServices: ['Catamaran Charter', 'Private Chef Lunch', 'Open Bar', 'Jet Ski Rentals'],
      pricePerPerson: 350,
      meetingPoint: 'Lekki Phase 1 Marina Berth 4',
      scheduleDays: ['Friday', 'Saturday', 'Sunday'],
    },
    location: {
      city: 'Lagos',
      country: 'Nigeria',
      address: 'Lekki Phase 1 Marina, Admiral Ayinla Way',
      latitude: 6.448,
      longitude: 3.472,
      neighborhoodDescription: 'Lekki Lagoon Marina',
    },
    starRating: 5,
    guestRating: 4.98,
    reviewCount: 64,
    heroImage: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1600&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80'],
    startingPrice: 350,
    currency: 'USD',
    currencySymbol: '$',
    featured: true,
    luxuryTier: 'Ocean Resort',
    amenities: ['Private Chef', 'Jet Ski', 'Open Champagne Bar', 'Snorkeling Equipment'],
    roomTypes: [],
    policies: {
      checkInTime: '09:00',
      checkOutTime: '17:00',
      cancellationDeadlineHours: 24,
      cancellationFeePercent: 0,
      petPolicy: 'No pets',
      smokingPolicy: 'Permitted on aft deck',
      childPolicy: 'Life jackets provided for all ages',
    },
    contactEmail: 'experiences@hotelstay.com',
    contactPhone: '+234 818 000 9999',
    status: 'approved',
    commissionRatePercent: 12.5,
    subscriptionPlan: 'starter',
    createdAt: '2026-03-01T00:00:00Z',
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [];
export const INITIAL_ROOMS: IndividualRoom[] = [];
export const INITIAL_GUESTS: GuestProfile[] = [];
export const INITIAL_STAFF: StaffMember[] = [];
export const INITIAL_HOUSEKEEPING: HousekeepingTask[] = [];
export const INITIAL_REVIEWS: Review[] = [];
export const INITIAL_TENANT_APPLICATIONS: TenantApplication[] = [];
export const INITIAL_PAYOUTS: PayoutRequest[] = [];
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];
