import {
  Hotel,
  IndividualRoom,
  Reservation,
  GuestProfile,
  StaffMember,
  HousekeepingTask,
  Review,
  TenantApplication,
  PayoutRequest,
  Destination,
  MobilityVehicle,
  DMCExperience,
  FlightRoute,
  NotificationItem,
} from './types';

// ==========================================
// 1. FIRST-CLASS DESTINATIONS DATABASE
// ==========================================
export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'dest-lagos',
    slug: 'lagos',
    city: 'Lagos',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Coastal Energy, Modern Architecture & Vibrant Terroir',
    description: 'A dynamic metropolis where Atlantic coastal breezes meet contemporary luxury retreats in Victoria Island, Ikoyi, and Eko Atlantic.',
    heroImage: 'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Lekki Conservation Sanctuary', 'Nike Art Gallery', 'Tarkwa Bay Private Yacht Haven', 'Victoria Island Culinary Quarter'],
    travelTips: ['Best visited November through March', 'Chauffeur airport transfer recommended from Murtala Muhammed International'],
    featured: true,
    climate: 'Tropical Savanna (28°C avg)',
    bestTimeToVisit: 'Nov – March',
  },
  {
    id: 'dest-abuja',
    slug: 'abuja',
    city: 'Abuja',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Monumental Granite Vistas & Diplomatic Serenity',
    description: 'Nigeria’s purpose-built capital framed by the iconic Aso Rock monolith, lush botanical gardens, and refined palatial residences.',
    heroImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Aso Rock Monolith', 'Millennium Park Botanical Arboretum', 'Maitama Diplomatic District', 'Usuma Dam Vista'],
    featured: true,
    climate: 'Tropical Continental (26°C avg)',
    bestTimeToVisit: 'Oct – April',
  },
  {
    id: 'dest-ibadan',
    slug: 'ibadan',
    city: 'Ibadan',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Historic Hills & Rich Yoruba Heritage',
    description: 'An ancient city of brown roofs and rolling green ridges, blossoming with bespoke eco-sanctuaries and cultural heritage sites.',
    heroImage: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Bower’s Tower Panoramas', 'Agodi Botanical Gardens', 'IITA Forest Reserve'],
    featured: false,
    climate: 'Warm Tropical (27°C avg)',
    bestTimeToVisit: 'Nov – Feb',
  },
  {
    id: 'dest-dubai',
    slug: 'dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
    headline: 'Futuristic Skyline, Arabian Dunes & Ultra-Luxury Living',
    description: 'The global benchmark for architectural daring, Michelin-starred culinary artistry, and private Arabian Gulf beach sanctuaries.',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Palm Jumeirah Archipelago', 'Dubai Opera & Downtown Fountains', 'Al Marmoom Desert Conservation Reserve'],
    featured: true,
    climate: 'Desert Subtropical (24°C winter / 38°C summer)',
    bestTimeToVisit: 'Nov – April',
  },
  {
    id: 'dest-abu-dhabi',
    slug: 'abu-dhabi',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    region: 'Middle East',
    headline: 'Island Sanctuaries & Cultural Masterpieces',
    description: 'From the Louvre Abu Dhabi dome to pristine Saadiyat Island beaches where hawksbill turtles nest in turquoise waters.',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [],
    attractions: ['Louvre Abu Dhabi', 'Sheikh Zayed Grand Mosque', 'Saadiyat Beach Sanctuary'],
    featured: false,
    climate: 'Arid Maritime',
    bestTimeToVisit: 'Oct – April',
  },
  {
    id: 'dest-paris',
    slug: 'paris',
    city: 'Paris',
    country: 'France',
    region: 'Western Europe',
    headline: 'Timeless Haussmannian Elegance & Haute Cuisine',
    description: 'Grand boulevards, private palace suites overlooking the Seine, and secluded courtyard boutique hotels.',
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Musée d’Orsay & Louvre', 'Jardin des Tuileries', 'Place Vendôme Jewelers', 'Le Marais Mansions'],
    featured: true,
    climate: 'Oceanic Mild',
    bestTimeToVisit: 'April – Oct',
  },
  {
    id: 'dest-santorini',
    slug: 'santorini',
    city: 'Santorini',
    country: 'Greece',
    region: 'Southern Europe',
    headline: 'Volcanic Calderas, Whitewashed Caves & Twilight Sunsets',
    description: 'Iconic clifftop cave sanctuaries carved into volcanic rock, offering heated infinity pools suspended over the sapphire Aegean Sea.',
    heroImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Oia Caldera Sunset Rim', 'Akrotiri Prehistoric Ruins', 'Red Sand Beach & Ammoudi Bay'],
    featured: true,
    climate: 'Mediterranean Sun (27°C avg summer)',
    bestTimeToVisit: 'May – Oct',
  },
  {
    id: 'dest-cape-town',
    slug: 'cape-town',
    city: 'Cape Town',
    country: 'South Africa',
    region: 'Southern Africa',
    headline: 'Granite Peaks, Atlantic Breakers & Wineland Estates',
    description: 'Where dramatic Table Mountain plunges into two oceans, bordered by historic Constantia vineyards and Camps Bay modern villas.',
    heroImage: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Table Mountain Aerial Cableway', 'Camps Bay Sunset Strip', 'Cape Point Nature Reserve', 'Franschhoek Wine Tram'],
    featured: true,
    climate: 'Mediterranean Coastal',
    bestTimeToVisit: 'Dec – March',
  },
  {
    id: 'dest-maldives',
    slug: 'maldives',
    city: 'North Malé Atoll',
    country: 'Maldives',
    region: 'Indian Ocean',
    headline: 'Overwater Villas & Luminous Coral Lagoons',
    description: 'Ultra-private stilt villas suspended over crystalline turquoise waters with private house reef diving.',
    heroImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [],
    attractions: ['Baa Atoll Biosphere Reserve', 'Undersea Dining Cellars', 'Bioluminescent Plankton Beaches'],
    featured: true,
    climate: 'Tropical Monsoonal',
    bestTimeToVisit: 'Nov – April',
  },
  {
    id: 'dest-inverness',
    slug: 'inverness',
    city: 'Inverness',
    country: 'United Kingdom',
    region: 'Northern Europe',
    headline: 'Highland Lochs, Ancient Pines & Heritage Castles',
    description: 'Secluded baronial stone estates surrounded by heather-clad glens, peat-smoked single malt distilleries, and deep freshwater lochs.',
    heroImage: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Loch Ness Panoramic Glens', 'Urquhart Castle Ruins', 'Cairngorms National Forest', 'Speyside Whisky Route'],
    featured: true,
    climate: 'Temperate Maritime',
    bestTimeToVisit: 'May – Sept',
  },
];

// ==========================================
// 2. VERIFIED INITIAL HOTELS
// ==========================================
export const INITIAL_HOTELS: Hotel[] = [
  {
    id: 'hotel-eko-royal',
    slug: 'eko-royal-sanctuary',
    name: 'The Eko Royal Sanctuary & Residences',
    tagline: 'Atlantic Panoramic Penthouse Suites & Private Helipad',
    description: 'Perched along the Atlantic waterfront of Victoria Island, The Eko Royal Sanctuary combines monolithic modernist concrete architecture with warm West African teak woodwork. Featuring private infinity plunge pools on every terrace, a bespoke art curation by leading contemporary African masters, and a dedicated 24-hour butler brigade.',
    managerId: 'persona-lagos-manager',
    managerEmail: 'adebayo@ekoroyal.ng',
    destinationId: 'dest-lagos',
    location: {
      city: 'Lagos',
      country: 'Nigeria',
      address: 'Plot 14 Admiralty Way, Victoria Island',
      latitude: 6.4281,
      longitude: 3.4219,
      neighborhoodDescription: 'Waterfront Victoria Island close to upscale art galleries, yacht marinas, and premier fine dining.',
    },
    starRating: 5,
    guestRating: 4.96,
    reviewCount: 84,
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
    ],
    categorizedPhotos: {
      cover: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80',
      exterior: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80'],
      lobby: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80'],
      rooms: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80'],
      dining: ['https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1200&q=80'],
      pool: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80'],
      facilities: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80'],
    },
    startingPrice: 620,
    currency: 'USD',
    currencySymbol: '$',
    featured: true,
    luxuryTier: '5-Star Luxury',
    amenities: [
      'Rooftop Ocean Infinity Pool',
      'Private Helipad Access',
      'Michelin-Caliber African Fusion Dining',
      'Holistic Thermal Spa & Hammam',
      'Chauffeured Armored Escort Available',
      '24/7 Dedicated Butler Service',
      'High-Speed Satellite Connectivity',
    ],
    roomTypes: [
      {
        id: 'eko-room-deluxe',
        hotelId: 'hotel-eko-royal',
        name: 'Atlantic Horizon Deluxe Suite',
        slug: 'atlantic-horizon-deluxe',
        description: 'Spacious ocean-facing sanctuary with private glass balcony, freestanding marble soaking tub, and custom mahogany furnishings.',
        sizeSqFt: 780,
        bedType: '1 King Bed',
        maxGuests: 2,
        view: 'Direct Atlantic Ocean Panorama',
        basePricePerNight: 620,
        images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80'],
        amenities: ['Private Balcony', 'Nespresso Atelier', 'Bang & Olufsen Sound', 'Marble Rain Shower'],
        cancellationPolicy: 'Free cancellation up to 48 hours prior to check-in.',
        mealPlan: 'Full Gourmet Breakfast Included',
        availableCount: 4,
      },
      {
        id: 'eko-room-penthouse',
        hotelId: 'hotel-eko-royal',
        name: 'The Presidential Imperial Penthouse',
        slug: 'presidential-imperial-penthouse',
        description: 'Two-story corner penthouse featuring a 12-meter private rooftop plunge pool, private boardroom, personal chef kitchen, and panoramic skyline vistas.',
        sizeSqFt: 2200,
        bedType: '2 Emperor King Beds',
        maxGuests: 4,
        view: '360° Atlantic Ocean & Lagos Island Skyline',
        basePricePerNight: 1850,
        images: ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80'],
        amenities: ['Private Plunge Pool', 'Private Chef Kitchen', 'Dedicated Butler', 'Executive Boardroom'],
        cancellationPolicy: 'Flexible cancellation with 72-hour window.',
        mealPlan: 'All Meals & Premium Cellar Inclusions',
        availableCount: 1,
      },
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellationDeadlineHours: 48,
      cancellationFeePercent: 0,
      petPolicy: 'Trained companion animals permitted upon prior concierge arrangement.',
      smokingPolicy: 'Strict non-smoking interiors. Designated outdoor cigar terrace.',
      childPolicy: 'Children of all ages welcomed. Family suites equipped with bespoke amenities.',
    },
    contactEmail: 'concierge@ekoroyal.ng',
    contactPhone: '+234 1 234 5678',
    website: 'https://hotelstay.com/hotel/eko-royal-sanctuary',
    status: 'approved',
    commissionRatePercent: 12.5,
    subscriptionPlan: 'enterprise',
  },
  {
    id: 'hotel-azure',
    slug: 'the-azure-riviera',
    name: 'The Azure Riviera Resort & Spa',
    tagline: 'Perched Mediterranean Sanctuary above Villefranche-sur-Mer',
    description: 'Immersed in terraced limestone cliffs overlooking the French Riviera, The Azure Riviera offers private infinity saltwater pools, fragrant stone pine gardens, and Michelin-starred Provencal dining.',
    managerId: 'persona-azure-admin',
    managerEmail: 'camille.laurent@azureriviera.com',
    destinationId: 'dest-paris',
    location: {
      city: 'Nice',
      country: 'France',
      address: '28 Boulevard de la Corniche, Villefranche-sur-Mer',
      latitude: 43.7034,
      longitude: 7.3112,
      neighborhoodDescription: 'Secluded cliffside private road minutes from Cap Ferrat and the old port.',
    },
    starRating: 5,
    guestRating: 4.98,
    reviewCount: 126,
    heroImage: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1400&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
    ],
    startingPrice: 850,
    currency: 'EUR',
    currencySymbol: '€',
    featured: true,
    luxuryTier: 'Ocean Resort',
    amenities: [
      'Infinity Cliffside Saltwater Pool',
      'Private Beach Club & Tender Dock',
      '2-Star Michelin Gourmet Restaurant',
      'Dior Prestige Holistic Spa',
      'Subterranean Vintage Wine Vault',
      'Helipad Transfer Service',
    ],
    roomTypes: [
      {
        id: 'azure-suite-cliff',
        hotelId: 'hotel-azure',
        name: 'Cap Ferrat Panorama Suite',
        slug: 'cap-ferrat-panorama',
        description: 'Suspended cliffside suite with private heated plunge pool, limestone terrace, and unobstructed Mediterranean horizon.',
        sizeSqFt: 950,
        bedType: '1 California King Bed',
        maxGuests: 2,
        view: 'Direct Mediterranean Sea & Cap Ferrat',
        basePricePerNight: 850,
        images: ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80'],
        amenities: ['Private Heated Plunge Pool', 'Dyson Supersonic Care', 'Dior Bath Amenities', 'Daily Champagne Hour'],
        cancellationPolicy: 'Free cancellation up to 72 hours before arrival.',
        mealPlan: 'Artisan French Breakfast in Suite Included',
        availableCount: 3,
      },
      {
        id: 'azure-villa-royal',
        hotelId: 'hotel-azure',
        name: 'The Grand Riviera Sovereign Villa',
        slug: 'grand-riviera-sovereign-villa',
        description: 'Independent 3-bedroom private estate with 15m infinity pool, olive garden, and dedicated private sommelier.',
        sizeSqFt: 3400,
        bedType: '3 King En-Suite Bedrooms',
        maxGuests: 6,
        view: 'Panoramic Coastal Horizon & Private Cove',
        basePricePerNight: 3200,
        images: ['https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1000&q=80'],
        amenities: ['15m Private Heated Pool', 'Private Chef & Butler', 'Yacht Charter Dock Access'],
        cancellationPolicy: 'Non-refundable within 7 days of arrival.',
        mealPlan: 'Full Private Chef Inclusions',
        availableCount: 1,
      },
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellationDeadlineHours: 72,
      cancellationFeePercent: 0,
      petPolicy: 'Small pets allowed under 10kg with pet concierge welcome package.',
      smokingPolicy: 'Non-smoking property.',
      childPolicy: 'Children over 6 welcomed with bespoke coastal discovery programmes.',
    },
    contactEmail: 'contact@azureriviera.com',
    contactPhone: '+33 4 93 01 23 45',
    status: 'approved',
    commissionRatePercent: 12.0,
    subscriptionPlan: 'enterprise',
  },
  {
    id: 'hotel-serenita',
    slug: 'serenita-coastal-haven',
    name: 'Serenita Coastal Haven & Caldera Spa',
    tagline: 'Volcanic Aegean Cliffside Cave Suites in Oia',
    description: 'Sculpted directly into the volcanic cliffs of Oia, Serenita offers unobstructed sunset views of the Aegean Caldera. Each cave suite features private heated mineral whirlpools, bespoke cycladic minimalist design, and hand-woven Greek linen furnishings.',
    managerId: 'persona-serenita-admin',
    managerEmail: 'dimitris@serenitahaven.gr',
    destinationId: 'dest-santorini',
    location: {
      city: 'Santorini',
      country: 'Greece',
      address: 'Oia Clifftop Walkway, Oia 84702',
      latitude: 36.4618,
      longitude: 25.3753,
      neighborhoodDescription: 'The quiet western flank of Oia cliff path with unobstructed sunset vistas.',
    },
    starRating: 5,
    guestRating: 4.95,
    reviewCount: 92,
    heroImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1400&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    ],
    startingPrice: 580,
    currency: 'EUR',
    currencySymbol: '€',
    featured: true,
    luxuryTier: 'Boutique',
    amenities: [
      'Caldera Infinity Cave Pool',
      'Private Mineral Heated Jacuzzi',
      'Cycladic Sunset Tasting Cellar',
      'Volcanic Stone Herbal Spa',
      'Private Catamaran Excursions',
    ],
    roomTypes: [
      {
        id: 'serenita-cave-suite',
        hotelId: 'hotel-serenita',
        name: 'Oia Sunset Caldera Cave Suite',
        slug: 'oia-sunset-caldera-cave',
        description: 'Traditional vaulted cave room with private heated jacuzzi tub carved into the cliff edge facing the Aegean sunset.',
        sizeSqFt: 650,
        bedType: '1 Custom Queen Stone Bed',
        maxGuests: 2,
        view: 'Santorini Caldera & Sunset Horizon',
        basePricePerNight: 580,
        images: ['https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1000&q=80'],
        amenities: ['Cliffside Jacuzzi', 'Santorini Assyrtiko Wine Welcome', 'Handmade Greek Organic Toiletries'],
        cancellationPolicy: 'Free cancellation up to 72 hours prior to arrival.',
        mealPlan: 'Champagne Greek Breakfast Served on Cliff Terrace',
        availableCount: 4,
      },
    ],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '11:00',
      cancellationDeadlineHours: 72,
      cancellationFeePercent: 0,
      petPolicy: 'Pets not permitted due to cliffside terrain.',
      smokingPolicy: 'Non-smoking suites.',
      childPolicy: 'Adults-only property (ages 16+).',
    },
    contactEmail: 'stay@serenitahaven.gr',
    contactPhone: '+30 2286 071234',
    status: 'approved',
    commissionRatePercent: 12.5,
    subscriptionPlan: 'pro',
  },
  {
    id: 'hotel-mirage-dubai',
    slug: 'the-palm-mirage-dubai',
    name: 'The Palm Mirage Island Palace',
    tagline: 'Ultra-Luxury Private Beachfront Mansions & Underwater Dining',
    description: 'An architectural triumph on the crescent of Palm Jumeirah. Featuring private Arabian Gulf beach cabanas, an Olympic-length freshwater infinity lagoon, and an undersea seafood conservatory.',
    managerId: 'persona-dubai-manager',
    managerEmail: 'tariq@palmmiragedubai.ae',
    destinationId: 'dest-dubai',
    location: {
      city: 'Dubai',
      country: 'United Arab Emirates',
      address: 'Crescent Road East, Palm Jumeirah',
      latitude: 25.1124,
      longitude: 55.139,
      neighborhoodDescription: 'Exclusive eastern crescent of Palm Jumeirah with panoramic views of the Dubai Marina skyline.',
    },
    starRating: 5,
    guestRating: 4.97,
    reviewCount: 158,
    heroImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1400&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    ],
    startingPrice: 920,
    currency: 'USD',
    currencySymbol: '$',
    featured: true,
    luxuryTier: '5-Star Luxury',
    amenities: [
      'Private 400m White Sand Beach',
      'Undersea Michelin Dining Room',
      'Rolls-Royce Phantom Chauffeur Fleet',
      'Private Yacht Mooring Buoys',
      'Gold Leaf Spa & Hammam Rituals',
    ],
    roomTypes: [
      {
        id: 'mirage-royal-suite',
        hotelId: 'hotel-mirage-dubai',
        name: 'Arabian Gulf Royal Lagoon Suite',
        slug: 'arabian-gulf-royal-lagoon',
        description: 'Opulent beachfront suite with private garden cabana, 24k gold accented marble bathroom, and direct lagoon plunge access.',
        sizeSqFt: 1100,
        bedType: '1 Royal King Bed',
        maxGuests: 2,
        view: 'Private Beach & Dubai Marina Skyline',
        basePricePerNight: 920,
        images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80'],
        amenities: ['Direct Beach Access', 'Personal Valet', 'Hermès Amenities', 'Private Bar Curation'],
        cancellationPolicy: 'Free cancellation up to 48 hours prior to check-in.',
        mealPlan: 'Royal Arabic & Continental Breakfast Buffet',
        availableCount: 3,
      },
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellationDeadlineHours: 48,
      cancellationFeePercent: 0,
      petPolicy: 'Pet friendly in designated garden villas.',
      smokingPolicy: 'Smoking permitted on private balconies only.',
      childPolicy: 'Full kids academy & childcare services available.',
    },
    contactEmail: 'vip@palmmiragedubai.ae',
    contactPhone: '+971 4 888 9999',
    status: 'approved',
    commissionRatePercent: 12.0,
    subscriptionPlan: 'enterprise',
  },
  {
    id: 'hotel-highland-loch',
    slug: 'highland-loch-pine-estate',
    name: 'Highland Loch & Pine Baronial Estate',
    tagline: 'Private 500-Acre Highland Wilderness & Peat Whisky Vault',
    description: 'A 19th-century baronial stone castle nestled on the secluded shores of Loch Ness. Featuring peat-burning fireplaces in every bedchamber, deer stalking reserves, and a world-renowned collection of rare single malt Scotch whiskies.',
    managerId: 'persona-scottish-manager',
    managerEmail: 'alastair@highlandpine.co.uk',
    destinationId: 'dest-inverness',
    location: {
      city: 'Inverness',
      country: 'United Kingdom',
      address: 'Loch Ness South Shore, Dores IV2 6TU',
      latitude: 57.3822,
      longitude: -4.3318,
      neighborhoodDescription: 'Historic private highland pine woodland directly on the calm waters of Loch Ness.',
    },
    starRating: 5,
    guestRating: 4.93,
    reviewCount: 67,
    heroImage: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1400&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80',
    ],
    startingPrice: 520,
    currency: 'GBP',
    currencySymbol: '£',
    featured: true,
    luxuryTier: 'Heritage Chateau',
    amenities: [
      'Private Loch-Facing Fireplace Chambers',
      'Peat Vault Rare Single Malt Bar',
      'Ghillie Guided Trout & Salmon Fishing',
      'Heated Cedarwood Hot Tubs in Pines',
      'Private Estate Land Rover Safaris',
    ],
    roomTypes: [
      {
        id: 'highland-baronial-chamber',
        hotelId: 'hotel-highland-loch',
        name: 'The Clan Fraser Baronial Chamber',
        slug: 'clan-fraser-baronial-chamber',
        description: 'Heritage four-poster mahogany bed, open stone fireplace, tartan wool armchairs, and bay windows framing Loch Ness.',
        sizeSqFt: 720,
        bedType: '1 Four-Poster King Bed',
        maxGuests: 2,
        view: 'Loch Ness & Caledonian Pine Forest',
        basePricePerNight: 520,
        images: ['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1000&q=80'],
        amenities: ['Wood-Burning Fireplace', 'Harris Tweed Furnishings', 'Dram of 18yr Whisky on Arrival'],
        cancellationPolicy: 'Free cancellation up to 5 days before arrival.',
        mealPlan: 'Traditional Scottish Cooked Breakfast Included',
        availableCount: 2,
      },
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellationDeadlineHours: 120,
      cancellationFeePercent: 0,
      petPolicy: 'Working dogs and well-behaved hounds welcomed.',
      smokingPolicy: 'Non-smoking castle interior.',
      childPolicy: 'Children over 8 welcomed.',
    },
    contactEmail: 'estatemanager@highlandpine.co.uk',
    contactPhone: '+44 1463 888 123',
    status: 'approved',
    commissionRatePercent: 12.5,
    subscriptionPlan: 'pro',
  },
];

// ==========================================
// 3. MOBILITY / CARS / CHAUFFEUR SERVICES
// ==========================================
export const INITIAL_VEHICLES: MobilityVehicle[] = [
  {
    id: 'veh-range-rover',
    name: 'Range Rover Autobiography SV LWB',
    category: 'SUV',
    passengers: 4,
    luggage: 4,
    transmission: 'Automatic',
    pricePerDay: 450,
    priceWithDriverPerHour: 85,
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1000&q=80',
    features: ['Executive Rear Seating', 'Panoramic Glass Sunroof', 'Chilled Console Fridge', 'Active Noise Cancellation', 'Armored Protection Available'],
    availableCities: ['Lagos', 'Abuja', 'Dubai', 'Paris', 'Nice'],
  },
  {
    id: 'veh-mercedes-s-class',
    name: 'Mercedes-Maybach S 680 4MATIC',
    category: 'Luxury Sedan',
    passengers: 3,
    luggage: 3,
    transmission: 'Automatic',
    pricePerDay: 580,
    priceWithDriverPerHour: 95,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1000&q=80',
    features: ['First-Class Rear Reclining Lounge', 'Silver Champagne Flutes', 'Burmester 4D High-End Sound', 'Rear Entertainment Screens'],
    availableCities: ['Lagos', 'Dubai', 'Paris', 'Nice', 'Santorini'],
  },
  {
    id: 'veh-mercedes-v-class',
    name: 'Mercedes-Benz V-Class VIP Executive Lounge',
    category: 'Executive Van',
    passengers: 6,
    luggage: 7,
    transmission: 'Automatic',
    pricePerDay: 390,
    priceWithDriverPerHour: 75,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80',
    features: ['Face-to-Face Conference Seating', 'Foldaway Mahogany Tables', 'Wi-Fi Hotspot 5G', 'Dual Privacy Scrim Glass'],
    availableCities: ['Lagos', 'Abuja', 'Dubai', 'Paris', 'Inverness'],
  },
  {
    id: 'veh-porsche-targa',
    name: 'Porsche 911 Targa 4 GTS Heritage',
    category: 'Convertible',
    passengers: 2,
    luggage: 2,
    transmission: 'Automatic',
    pricePerDay: 620,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80',
    features: ['Aero Targa Open Roof', 'Sport Chrono Package', 'Bespoke Houndstooth Leather', 'All-Wheel Drive Coastal Grip'],
    availableCities: ['Nice', 'Dubai', 'Santorini', 'Cape Town'],
  },
];

// ==========================================
// 4. DMC / EXPERIENCES & TOURS
// ==========================================
export const INITIAL_EXPERIENCES: DMCExperience[] = [
  {
    id: 'dmc-lagos-art-culinary',
    title: 'Lagos Modern Masterpieces & Atlantic Yacht Safari',
    slug: 'lagos-modern-art-yacht-safari',
    category: 'Tours',
    destinationCity: 'Lagos',
    destinationCountry: 'Nigeria',
    durationDays: 3,
    pricePerPerson: 1250,
    heroImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Private private curator tour of Nike Art Gallery with founder Madam Nike Okundaye',
      'Sunset champagne cruise along Tarkwa Bay & Eko Atlantic coastline on private 55ft yacht',
      'Exclusive 7-course tasting menu with leading contemporary Nigerian culinary pioneers',
    ],
    includedServices: ['Private Chauffeur', 'Yacht Charter', 'All Tastings & Admissions', 'Dedicated Concierge Escort'],
    description: 'An immersive 3-day deep dive into the creative explosion and coastal opulence of modern Lagos, curated for discerning collectors and cultural connoisseurs.',
  },
  {
    id: 'dmc-santorini-catamaran',
    title: 'Santorini Caldera Sunset Catamaran & Volcanic Terroir',
    slug: 'santorini-caldera-catamaran-terroir',
    category: 'Tours',
    destinationCity: 'Santorini',
    destinationCountry: 'Greece',
    durationDays: 1,
    pricePerPerson: 420,
    heroImage: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Private Lagoon 450 catamaran charter navigating the volcanic caldera and hot springs',
      'Gourmet barbecue prepared onboard with fresh Aegean seafood and indigenous herbs',
      'Exclusive private cellar tasting of rare vintage Assyrtiko wines in Pyrgos',
    ],
    includedServices: ['Catamaran Charter', 'Sommelier Guided Tasting', 'Gourmet Lunch & Drinks', 'Hotel Transfers'],
    description: 'Sail the sapphire waters of the volcanic caldera, swim in secluded mineral coves, and savor rare volcanic wines as the sun sets over Oia.',
  },
  {
    id: 'dmc-honeymoon-retreat',
    title: 'The Sovereign Aegean & Maldivian Honeymoon Odyssey',
    slug: 'sovereign-aegean-honeymoon-odyssey',
    category: 'Honeymoon Packages',
    destinationCity: 'Santorini',
    destinationCountry: 'Greece',
    durationDays: 7,
    pricePerPerson: 3800,
    heroImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Cliffside private plunge pool cave villa with daily in-suite vintage champagne breakfast',
      'Couples twilight herbal thermal spa ritual under the Mediterranean stars',
      'Helicopter aerial tour over Mykonos, Delos, and the Cycladic archipelago',
    ],
    includedServices: ['7 Nights Luxury Stay', 'Helicopter Transfers', 'All Spa Rituals', 'Private Concierge Manager'],
    description: 'Designed for couples embarking on a lifetime together, combining absolute privacy, restorative romance, and world-class hospitality.',
  },
  {
    id: 'dmc-events-gala',
    title: 'Bespoke Destination Weddings & Executive Summits',
    slug: 'destination-weddings-executive-summits',
    category: 'Events',
    destinationCity: 'Dubai',
    destinationCountry: 'United Arab Emirates',
    durationDays: 4,
    pricePerPerson: 2500,
    heroImage: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Exclusive buyout coordination of private beachfront island estates',
      'World-class acoustic staging, floral master installations, and Michelin culinary brigades',
      'Full VIP protocol security and discrete diplomatic delegation handling',
    ],
    includedServices: ['Event Production Director', 'Full Venue Buyout Management', 'VIP Transport Fleet', 'Catering Architecture'],
    description: 'Turnkey event planning and executive destination management for milestones, international summits, and royal ceremonies.',
  },
];

// ==========================================
// 5. FLIGHT DISCOVERY ROUTES
// ==========================================
export const INITIAL_FLIGHTS: FlightRoute[] = [
  {
    id: 'fl-lon-los',
    fromCity: 'London',
    fromCode: 'LHR',
    toCity: 'Lagos',
    toCode: 'LOS',
    airline: 'Virgin Atlantic / British Airways',
    duration: '6h 35m',
    indicativePrice: 780,
    cabinClasses: ['Economy', 'Premium Economy', 'Upper Class / Club World'],
    direct: true,
  },
  {
    id: 'fl-cdg-dxb',
    fromCity: 'Paris',
    fromCode: 'CDG',
    toCity: 'Dubai',
    toCode: 'DXB',
    airline: 'Emirates / Air France',
    duration: '6h 45m',
    indicativePrice: 650,
    cabinClasses: ['Economy', 'Business', 'First Class Suite'],
    direct: true,
  },
  {
    id: 'fl-jfk-nce',
    fromCity: 'New York',
    fromCode: 'JFK',
    toCity: 'Nice',
    toCode: 'NCE',
    airline: 'La Compagnie / Delta',
    duration: '7h 50m',
    indicativePrice: 940,
    cabinClasses: ['All-Business Class', 'Delta One'],
    direct: true,
  },
  {
    id: 'fl-fra-jtr',
    fromCity: 'Frankfurt',
    fromCode: 'FRA',
    toCity: 'Santorini',
    toCode: 'JTR',
    airline: 'Lufthansa',
    duration: '3h 10m',
    indicativePrice: 320,
    cabinClasses: ['Economy', 'Business'],
    direct: true,
  },
];

// ==========================================
// 6. INITIAL RESERVATIONS
// ==========================================
export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'HS-78921',
    hotelId: 'hotel-eko-royal',
    hotelName: 'The Eko Royal Sanctuary & Residences',
    hotelCity: 'Lagos',
    hotelImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
    roomTypeId: 'eko-room-deluxe',
    roomTypeName: 'Atlantic Horizon Deluxe Suite',
    roomNumber: 'Suite 402',
    guestId: 'persona-guest',
    guestName: 'Julian Vance',
    guestEmail: 'julian.vance@vanceholdings.co.uk',
    guestPhone: '+44 7911 123456',
    checkInDate: '2026-09-24',
    checkOutDate: '2026-09-28',
    nightsCount: 4,
    guestsCount: { adults: 2, children: 0 },
    basePrice: 2480,
    taxesAndFees: 297,
    extrasTotal: 180,
    discountAmount: 0,
    totalAmount: 2957,
    status: 'confirmed',
    paymentStatus: 'paid',
    bookingSource: 'Marketplace',
    specialRequests: 'High floor ocean-facing preferred. Chilled sparkling mineral water upon arrival.',
    selectedExtras: [{ name: 'Private Armored Chauffeur Transfer', price: 180 }],
    createdAt: '2026-09-14 10:24',
  },
];

export const INITIAL_ROOMS: IndividualRoom[] = [
  {
    id: 'rm-eko-401',
    hotelId: 'hotel-eko-royal',
    roomNumber: '401',
    roomTypeId: 'eko-room-deluxe',
    roomTypeName: 'Atlantic Horizon Deluxe Suite',
    floor: 4,
    status: 'available',
    lastCleaned: '2026-09-14 09:00',
  },
  {
    id: 'rm-eko-402',
    hotelId: 'hotel-eko-royal',
    roomNumber: '402',
    roomTypeId: 'eko-room-deluxe',
    roomTypeName: 'Atlantic Horizon Deluxe Suite',
    floor: 4,
    status: 'reserved',
    currentGuestName: 'Julian Vance',
    currentReservationId: 'HS-78921',
    lastCleaned: '2026-09-14 11:30',
  },
];

export const INITIAL_GUESTS: GuestProfile[] = [
  {
    id: 'guest-julian',
    hotelId: 'hotel-eko-royal',
    fullName: 'Julian Vance',
    email: 'julian.vance@vanceholdings.co.uk',
    phone: '+44 7911 123456',
    country: 'United Kingdom',
    totalStays: 4,
    lifetimeSpend: 11840,
    vipStatus: true,
    preferences: ['High Floor', 'Quiet Suite', 'Sparkling Water', 'Late Checkout 3PM'],
    lastStayDate: '2026-06-12',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'staff-adebayo',
    hotelId: 'hotel-eko-royal',
    fullName: 'Adebayo Adeleke',
    email: 'adebayo@ekoroyal.ng',
    role: 'General Manager',
    phone: '+234 803 123 4567',
    status: 'active',
    lastActive: 'Just now',
  },
];

export const INITIAL_HOUSEKEEPING: HousekeepingTask[] = [
  {
    id: 'hk-1',
    hotelId: 'hotel-eko-royal',
    roomNumber: '402',
    taskType: 'Full Turnover',
    assignedTo: 'Ngozi E.',
    priority: 'High',
    status: 'completed',
    dueDate: '2026-09-24',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    hotelId: 'hotel-eko-royal',
    authorName: 'Lord Sterling Campbell',
    authorLocation: 'London, UK',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    subRatings: { cleanliness: 5, comfort: 5, location: 5, service: 5, value: 5 },
    date: 'August 2026',
    title: 'An absolute masterpiece of West African luxury hospitality',
    comment: 'The architectural design and level of intuitive service rival the finest palatial hotels in Paris and Tokyo. The rooftop ocean views and chauffeur transfers made our Lagos stay completely effortless.',
    verifiedBooking: true,
  },
  {
    id: 'rev-2',
    hotelId: 'hotel-azure',
    authorName: 'Isabella Van Der Bilt',
    authorLocation: 'Amsterdam, Netherlands',
    rating: 5,
    subRatings: { cleanliness: 5, comfort: 5, location: 5, service: 5, value: 4.8 },
    date: 'July 2026',
    title: 'Unrivaled Mediterranean cliffside sanctuary',
    comment: 'The privacy of the terrace plunge pool and the sommelier wine cellar tour exceeded every expectation. We have already booked our return visit.',
    verifiedBooking: true,
  },
];

export const INITIAL_TENANT_APPLICATIONS: TenantApplication[] = [
  {
    id: 'app-maitama-grand',
    hotelName: 'Maitama Grand Regency Palace',
    applicantName: 'Dr. Ibrahim Bello',
    applicantEmail: 'ibrahim@maitamagrand.ng',
    location: 'Maitama, Abuja, Nigeria',
    roomsCount: 42,
    starRatingProposed: 5,
    requestedTier: 'enterprise',
    status: 'pending',
    submittedAt: '2026-09-15 14:10',
    notes: 'Diplomatic quarter luxury property with private conference pavilion and presidential suites.',
  },
];

export const INITIAL_PAYOUTS: PayoutRequest[] = [
  {
    id: 'pay-001',
    hotelId: 'hotel-eko-royal',
    hotelName: 'The Eko Royal Sanctuary & Residences',
    amount: 14800,
    currency: 'USD',
    period: 'September 1 – 15, 2026',
    status: 'pending',
    bankAccountLast4: '8839',
    requestedAt: '2026-09-15',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'persona-guest',
    title: 'Booking Confirmed (HS-78921)',
    message: 'Your reservation at The Eko Royal Sanctuary & Residences is confirmed for Sep 24 – 28, 2026.',
    type: 'booking',
    date: '10 mins ago',
    read: false,
    linkUrl: '/guest?tab=upcoming',
  },
  {
    id: 'notif-2',
    userId: 'persona-guest',
    title: 'Welcome to HotelStay Privé',
    message: 'Enjoy complimentary upgrades, gourmet breakfast, and late checkout privileges across participating properties.',
    type: 'promotion',
    date: '2 hours ago',
    read: true,
  },
];
