import {
  Hotel,
  IndividualRoom,
  Reservation,
  GuestProfile,
  StaffMember,
  HousekeepingTask,
  Review,
  TenantApplication,
  PayoutRequest,
  Destination,
  MobilityVehicle,
  DMCExperience,
  FlightRoute,
  NotificationItem,
} from './types';

// ==========================================
// 1. FIRST-CLASS DESTINATIONS DATABASE
// ==========================================
export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'dest-lagos',
    slug: 'lagos',
    city: 'Lagos',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Coastal Energy, Modern Architecture & Vibrant Terroir',
    description: 'A dynamic metropolis where Atlantic coastal breezes meet contemporary luxury retreats in Victoria Island, Ikoyi, and Eko Atlantic.',
    heroImage: 'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Lekki Conservation Sanctuary', 'Nike Art Gallery', 'Tarkwa Bay Private Yacht Haven', 'Victoria Island Culinary Quarter'],
    travelTips: ['Best visited November through March', 'Chauffeur airport transfer recommended from Murtala Muhammed International'],
    featured: true,
    climate: 'Tropical Savanna (28°C avg)',
    bestTimeToVisit: 'Nov – March',
  },
  {
    id: 'dest-abuja',
    slug: 'abuja',
    city: 'Abuja',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Monumental Granite Vistas & Diplomatic Serenity',
    description: 'Nigeria’s purpose-built capital framed by the iconic Aso Rock monolith, lush botanical gardens, and refined palatial residences.',
    heroImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Aso Rock Monolith', 'Millennium Park Botanical Arboretum', 'Maitama Diplomatic District', 'Usuma Dam Vista'],
    featured: true,
    climate: 'Tropical Continental (26°C avg)',
    bestTimeToVisit: 'Oct – April',
  },
  {
    id: 'dest-ibadan',
    slug: 'ibadan',
    city: 'Ibadan',
    country: 'Nigeria',
    region: 'West Africa',
    headline: 'Historic Hills & Rich Yoruba Heritage',
    description: 'An ancient city of brown roofs and rolling green ridges, blossoming with bespoke eco-sanctuaries and cultural heritage sites.',
    heroImage: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Bower’s Tower Panoramas', 'Agodi Botanical Gardens', 'IITA Forest Reserve'],
    featured: false,
    climate: 'Warm Tropical (27°C avg)',
    bestTimeToVisit: 'Nov – Feb',
  },
  {
    id: 'dest-dubai',
    slug: 'dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
    headline: 'Futuristic Skyline, Arabian Dunes & Ultra-Luxury Living',
    description: 'The global benchmark for architectural daring, Michelin-starred culinary artistry, and private Arabian Gulf beach sanctuaries.',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Palm Jumeirah Archipelago', 'Dubai Opera & Downtown Fountains', 'Al Marmoom Desert Conservation Reserve'],
    featured: true,
    climate: 'Desert Subtropical (24°C winter / 38°C summer)',
    bestTimeToVisit: 'Nov – April',
  },
  {
    id: 'dest-abu-dhabi',
    slug: 'abu-dhabi',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    region: 'Middle East',
    headline: 'Island Sanctuaries & Cultural Masterpieces',
    description: 'From the Louvre Abu Dhabi dome to pristine Saadiyat Island beaches where hawksbill turtles nest in turquoise waters.',
    heroImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [],
    attractions: ['Louvre Abu Dhabi', 'Sheikh Zayed Grand Mosque', 'Saadiyat Beach Sanctuary'],
    featured: false,
    climate: 'Arid Maritime',
    bestTimeToVisit: 'Oct – April',
  },
  {
    id: 'dest-paris',
    slug: 'paris',
    city: 'Paris',
    country: 'France',
    region: 'Western Europe',
    headline: 'Timeless Haussmannian Elegance & Haute Cuisine',
    description: 'Grand boulevards, private palace suites overlooking the Seine, and secluded courtyard boutique hotels.',
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Musée d’Orsay & Louvre', 'Jardin des Tuileries', 'Place Vendôme Jewelers', 'Le Marais Mansions'],
    featured: true,
    climate: 'Oceanic Mild',
    bestTimeToVisit: 'April – Oct',
  },
  {
    id: 'dest-santorini',
    slug: 'santorini',
    city: 'Santorini',
    country: 'Greece',
    region: 'Southern Europe',
    headline: 'Volcanic Calderas, Whitewashed Caves & Twilight Sunsets',
    description: 'Iconic clifftop cave sanctuaries carved into volcanic rock, offering heated infinity pools suspended over the sapphire Aegean Sea.',
    heroImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Oia Caldera Sunset Rim', 'Akrotiri Prehistoric Ruins', 'Red Sand Beach & Ammoudi Bay'],
    featured: true,
    climate: 'Mediterranean Sun (27°C avg summer)',
    bestTimeToVisit: 'May – Oct',
  },
  {
    id: 'dest-cape-town',
    slug: 'cape-town',
    city: 'Cape Town',
    country: 'South Africa',
    region: 'Southern Africa',
    headline: 'Granite Peaks, Atlantic Breakers & Wineland Estates',
    description: 'Where dramatic Table Mountain plunges into two oceans, bordered by historic Constantia vineyards and Camps Bay modern villas.',
    heroImage: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Table Mountain Aerial Cableway', 'Camps Bay Sunset Strip', 'Cape Point Nature Reserve', 'Franschhoek Wine Tram'],
    featured: true,
    climate: 'Mediterranean Coastal',
    bestTimeToVisit: 'Dec – March',
  },
  {
    id: 'dest-maldives',
    slug: 'maldives',
    city: 'North Malé Atoll',
    country: 'Maldives',
    region: 'Indian Ocean',
    headline: 'Overwater Villas & Luminous Coral Lagoons',
    description: 'Ultra-private stilt villas suspended over crystalline turquoise waters with private house reef diving.',
    heroImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [],
    attractions: ['Baa Atoll Biosphere Reserve', 'Undersea Dining Cellars', 'Bioluminescent Plankton Beaches'],
    featured: true,
    climate: 'Tropical Monsoonal',
    bestTimeToVisit: 'Nov – April',
  },
  {
    id: 'dest-inverness',
    slug: 'inverness',
    city: 'Inverness',
    country: 'United Kingdom',
    region: 'Northern Europe',
    headline: 'Highland Lochs, Ancient Pines & Heritage Castles',
    description: 'Secluded baronial stone estates surrounded by heather-clad glens, peat-smoked single malt distilleries, and deep freshwater lochs.',
    heroImage: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: ['Loch Ness Panoramic Glens', 'Urquhart Castle Ruins', 'Cairngorms National Forest', 'Speyside Whisky Route'],
    featured: true,
    climate: 'Temperate Maritime',
    bestTimeToVisit: 'May – Sept',
  },
];

// ==========================================
// 2. REAL ONBOARDED HOTELS (Empty until onboarded via OPERATE)
// ==========================================
// 2. REAL ONBOARDED HOTELS (Empty until onboarded via OPERATE)
// ==========================================
export const INITIAL_HOTELS: Hotel[] = [];

// ==========================================
// 3. MOBILITY / CARS / CHAUFFEUR SERVICES
// ==========================================
export const INITIAL_VEHICLES: MobilityVehicle[] = [
  {
    id: 'veh-range-rover',
    name: 'Range Rover Autobiography SV LWB',
    category: 'SUV',
    passengers: 4,
    luggage: 4,
    transmission: 'Automatic',
    pricePerDay: 450,
    priceWithDriverPerHour: 85,
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1000&q=80',
    features: ['Executive Rear Seating', 'Panoramic Glass Sunroof', 'Chilled Console Fridge', 'Active Noise Cancellation', 'Armored Protection Available'],
    availableCities: ['Lagos', 'Abuja', 'Dubai', 'Paris', 'Nice'],
  },
  {
    id: 'veh-mercedes-s-class',
    name: 'Mercedes-Maybach S 680 4MATIC',
    category: 'Luxury Sedan',
    passengers: 3,
    luggage: 3,
    transmission: 'Automatic',
    pricePerDay: 580,
    priceWithDriverPerHour: 95,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1000&q=80',
    features: ['First-Class Rear Reclining Lounge', 'Silver Champagne Flutes', 'Burmester 4D High-End Sound', 'Rear Entertainment Screens'],
    availableCities: ['Lagos', 'Dubai', 'Paris', 'Nice', 'Santorini'],
  },
  {
    id: 'veh-mercedes-v-class',
    name: 'Mercedes-Benz V-Class VIP Executive Lounge',
    category: 'Executive Van',
    passengers: 6,
    luggage: 7,
    transmission: 'Automatic',
    pricePerDay: 390,
    priceWithDriverPerHour: 75,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80',
    features: ['Face-to-Face Conference Seating', 'Foldaway Mahogany Tables', 'Wi-Fi Hotspot 5G', 'Dual Privacy Scrim Glass'],
    availableCities: ['Lagos', 'Abuja', 'Dubai', 'Paris', 'Inverness'],
  },
  {
    id: 'veh-porsche-targa',
    name: 'Porsche 911 Targa 4 GTS Heritage',
    category: 'Convertible',
    passengers: 2,
    luggage: 2,
    transmission: 'Automatic',
    pricePerDay: 620,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80',
    features: ['Aero Targa Open Roof', 'Sport Chrono Package', 'Bespoke Houndstooth Leather', 'All-Wheel Drive Coastal Grip'],
    availableCities: ['Nice', 'Dubai', 'Santorini', 'Cape Town'],
  },
];

// ==========================================
// 4. DMC / EXPERIENCES & TOURS
// ==========================================
export const INITIAL_EXPERIENCES: DMCExperience[] = [
  {
    id: 'dmc-lagos-art-culinary',
    title: 'Lagos Modern Masterpieces & Atlantic Yacht Safari',
    slug: 'lagos-modern-art-yacht-safari',
    category: 'Tours',
    destinationCity: 'Lagos',
    destinationCountry: 'Nigeria',
    durationDays: 3,
    pricePerPerson: 1250,
    heroImage: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Private private curator tour of Nike Art Gallery with founder Madam Nike Okundaye',
      'Sunset champagne cruise along Tarkwa Bay & Eko Atlantic coastline on private 55ft yacht',
      'Exclusive 7-course tasting menu with leading contemporary Nigerian culinary pioneers',
    ],
    includedServices: ['Private Chauffeur', 'Yacht Charter', 'All Tastings & Admissions', 'Dedicated Concierge Escort'],
    description: 'An immersive 3-day deep dive into the creative explosion and coastal opulence of modern Lagos, curated for discerning collectors and cultural connoisseurs.',
  },
  {
    id: 'dmc-santorini-catamaran',
    title: 'Santorini Caldera Sunset Catamaran & Volcanic Terroir',
    slug: 'santorini-caldera-catamaran-terroir',
    category: 'Tours',
    destinationCity: 'Santorini',
    destinationCountry: 'Greece',
    durationDays: 1,
    pricePerPerson: 420,
    heroImage: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Private Lagoon 450 catamaran charter navigating the volcanic caldera and hot springs',
      'Gourmet barbecue prepared onboard with fresh Aegean seafood and indigenous herbs',
      'Exclusive private cellar tasting of rare vintage Assyrtiko wines in Pyrgos',
    ],
    includedServices: ['Catamaran Charter', 'Sommelier Guided Tasting', 'Gourmet Lunch & Drinks', 'Hotel Transfers'],
    description: 'Sail the sapphire waters of the volcanic caldera, swim in secluded mineral coves, and savor rare volcanic wines as the sun sets over Oia.',
  },
  {
    id: 'dmc-honeymoon-retreat',
    title: 'The Sovereign Aegean & Maldivian Honeymoon Odyssey',
    slug: 'sovereign-aegean-honeymoon-odyssey',
    category: 'Honeymoon Packages',
    destinationCity: 'Santorini',
    destinationCountry: 'Greece',
    durationDays: 7,
    pricePerPerson: 3800,
    heroImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Cliffside private plunge pool cave villa with daily in-suite vintage champagne breakfast',
      'Couples twilight herbal thermal spa ritual under the Mediterranean stars',
      'Helicopter aerial tour over Mykonos, Delos, and the Cycladic archipelago',
    ],
    includedServices: ['7 Nights Luxury Stay', 'Helicopter Transfers', 'All Spa Rituals', 'Private Concierge Manager'],
    description: 'Designed for couples embarking on a lifetime together, combining absolute privacy, restorative romance, and world-class hospitality.',
  },
  {
    id: 'dmc-events-gala',
    title: 'Bespoke Destination Weddings & Executive Summits',
    slug: 'destination-weddings-executive-summits',
    category: 'Events',
    destinationCity: 'Dubai',
    destinationCountry: 'United Arab Emirates',
    durationDays: 4,
    pricePerPerson: 2500,
    heroImage: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1000&q=80'],
    highlights: [
      'Exclusive buyout coordination of private beachfront island estates',
      'World-class acoustic staging, floral master installations, and Michelin culinary brigades',
      'Full VIP protocol security and discrete diplomatic delegation handling',
    ],
    includedServices: ['Event Production Director', 'Full Venue Buyout Management', 'VIP Transport Fleet', 'Catering Architecture'],
    description: 'Turnkey event planning and executive destination management for milestones, international summits, and royal ceremonies.',
  },
];

// ==========================================
// 5. FLIGHT DISCOVERY ROUTES
// ==========================================
export const INITIAL_FLIGHTS: FlightRoute[] = [
  {
    id: 'fl-lon-los',
    fromCity: 'London',
    fromCode: 'LHR',
    toCity: 'Lagos',
    toCode: 'LOS',
    airline: 'Virgin Atlantic / British Airways',
    duration: '6h 35m',
    indicativePrice: 780,
    cabinClasses: ['Economy', 'Premium Economy', 'Upper Class / Club World'],
    direct: true,
  },
  {
    id: 'fl-cdg-dxb',
    fromCity: 'Paris',
    fromCode: 'CDG',
    toCity: 'Dubai',
    toCode: 'DXB',
    airline: 'Emirates / Air France',
    duration: '6h 45m',
    indicativePrice: 650,
    cabinClasses: ['Economy', 'Business', 'First Class Suite'],
    direct: true,
  },
  {
    id: 'fl-jfk-nce',
    fromCity: 'New York',
    fromCode: 'JFK',
    toCity: 'Nice',
    toCode: 'NCE',
    airline: 'La Compagnie / Delta',
    duration: '7h 50m',
    indicativePrice: 940,
    cabinClasses: ['All-Business Class', 'Delta One'],
    direct: true,
  },
  {
    id: 'fl-fra-jtr',
    fromCity: 'Frankfurt',
    fromCode: 'FRA',
    toCity: 'Santorini',
    toCode: 'JTR',
    airline: 'Lufthansa',
    duration: '3h 10m',
    indicativePrice: 320,
    cabinClasses: ['Economy', 'Business'],
    direct: true,
  },
];

// ==========================================
// 6. OPERATIONAL COLLECTIONS (Populated dynamically upon real onboarding & bookings)
// ==========================================
export const INITIAL_RESERVATIONS: Reservation[] = [];
export const INITIAL_ROOMS: IndividualRoom[] = [];
export const INITIAL_GUESTS: GuestProfile[] = [];
export const INITIAL_STAFF: StaffMember[] = [];
export const INITIAL_HOUSEKEEPING: HousekeepingTask[] = [];
export const INITIAL_REVIEWS: Review[] = [];
export const INITIAL_TENANT_APPLICATIONS: TenantApplication[] = [];
export const INITIAL_PAYOUTS: PayoutRequest[] = [];
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];
